from sqlalchemy import create_engine, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, Session
from typing import Optional
from datetime import datetime
from sqlalchemy import select 


# --- Engine: Connects to a SQLite database file ---
engine = create_engine(
    "sqlite:///product.db",
    echo=True,  # echo=True will log all the SQL statements generated by SQLAlchemy to the console, which is useful for debugging and understanding what queries are being executed.
)

# --- Base class: all models inherit from this ---
class Base(DeclarativeBase):
    pass

# Creating the two models: Category and Product
class Category(Base):
    __tablename__ = "Categories" # The actual table name in the database

    id: Mapped[int] = mapped_column(primary_key = True)
    name: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    description: Mapped[Optional[str]] = mapped_column(String(500)) # Optional — can be NULL
   
    def __repr__(self) -> str:
        return f"Category(id={self.id}, name='{self.name}',description='{self.description}')"

class Product(Base):
    __tablename__ = "Products"  # The actual table name in the database

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    price: Mapped[float] = mapped_column(nullable=False)
    in_stock: Mapped[bool] = mapped_column(default=True)
    category_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    def __repr__(self):
        return f"<Product(id={self.id}, name='{self.name}', price={self.price})>"
 
 
if __name__ == "__main__":
    # Create the tables in product_catalog.db
    Base.metadata.create_all(engine)
    print("Tables created successfully in product.db")


# Create a Session

with Session(engine) as session:
    # Create category objects

    electronics = Category(name = "Electronics")
    session.add(electronics)

    books = Category(name = "Books")
    session.add(books)

    school_supplies = Category(name = "School Supplies")
    session.add(school_supplies)

    session.commit()

    # Inserting products

    products = [
        Product(name="Wireless Mouse", price=24.99, in_stock=True, category_name="Electronics"),
        Product(name = "Wireless Keyboard", price=35.50, in_stock=True, category_name = "Electronics"),
        Product(name="Bose Noise-Cancelling Headphones", price=149.99, in_stock=False,category_name="Electronics"),
        Product(name="Guide to Python 101", price=80.10, in_stock=False, category_name="Books"),
        Product(name="Mechanical Pencil", price=5.99, in_stock=False, category_name="School Supplies"),
        Product(name="College Ruled Notebook", price=6.99, in_stock=False, category_name="School Supplies"),
        Product(name="Ruler", price=6.99, in_stock=False, category_name="School Supplies"),
        ] 

    session.add_all(products)
    session.commit()

    # --- Query and print all categories ---
    print("\n--- All Categories ---")
    all_categories = session.execute(select(Category)).scalars().all()
    for category in all_categories:
        print(category)

    # --- Query and print all products that are in stock ---
    print("\n--- Products In Stock ---")
    in_stock_products = session.execute(
    select(Product).where(Product.in_stock == True)
    ).scalars().all()
    for product in in_stock_products:
        print(product)

    # --- Query and print all products with a price under $50 ---
    print("\n--- Products Under $50 ---")
    cheap_products = session.execute(select(Product).where(Product.price < 50)).scalars().all()
    for product in cheap_products:
        print(product)
 